### ISSUE TITLE
still NPE when handler is not set

### ISSUE THREAD

**Issue by ericbottard** [projectriff/java-function-invoker#107]
In the "function is a class but not a bean" case, if the user forgets to set the handler, the invoker throws a NPE like so:

```
	... 17 more
Caused by: java.lang.NullPointerException
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration$BeanCreator.getFunctionNames(FunctionCreatorConfiguration.java:392)
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.functionNames(FunctionCreatorConfiguration.java:138)
	at org.springframework.cloud.function.deployer.FunctionCreatorConfiguration.init(FunctionCreatorConfiguration.java:119)
```

Should fail more explicitly

**Comment by trisberg** [comment]
I wonder if the snapshot build of the java-function-invoker is stale/outdated, let me upload a new one and see if it fixes this issue

**Comment by trisberg** [comment]
That wasn't the case. It seems to only happen when the app is built with the buildpack. I can run the same command after copying the invoker jar and the app files to a `/workspace/app` directory on my Mac and I don't get the NPE.

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/bin/java -jar /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-20181113.142238-1-exec.jar $JAVA_OPTS --function.uri='file:///workspace/app'
```

results in:

```
Caused by: java.lang.IllegalStateException: No function bean locator provided, please configure function.bean as a bean name or class name.
	at org.springframework.cloud.function.deployer.FunctionProperties.init(FunctionProperties.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 30 more
```

**Comment by trisberg** [comment]
Java version on my Mac:

```
$ /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/bin/java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

Java version for builder:

```
$ java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)
```

**Comment by trisberg** [comment]
I wonder if there is some caching going on in the buildpack process. This is the jar file in the app container:

```
$ ls -l /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-20181113.142238-1-exec.jar 
-rwxr-xr-x 1 pack pack 18920150 Nov 13 16:19 /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-20181113.142238-1-exec.jar
$ sha256sum /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-20181113.142238-1-exec.jar 
1c185acbde7e1f848d64a5e6c290e098e379b372aaf0268b871a680222e78273  /workspace/io.projectriff.riff/riff-invoker-java/java-function-invoker-0.1.3-20181113.142238-1-exec.jar
```

This is the jar file downloaded directly from repo.spring.io:

```
$ ls -l java-function-invoker-0.1.3-20181113.142238-1-exec.jar 
-rw-r--r-- 1 pack pack 18895480 Nov 13 21:18 java-function-invoker-0.1.3-20181113.142238-1-exec.jar
$ sha256sum java-function-invoker-0.1.3-20181113.142238-1-exec.jar 
ba07f13a2a0e4713dd52bc859b9922186cab876897d702c88c5581e07fce478f  java-function-invoker-0.1.3-20181113.142238-1-exec.jar
```

**Comment by trisberg** [comment]
If I run with the downloaded jar file I get the correct exception:

```
Caused by: java.lang.IllegalStateException: No function bean locator provided, please configure function.bean as a bean name or class name.
	at org.springframework.cloud.function.deployer.FunctionProperties.init(FunctionProperties.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 30 more
```

**Comment by trisberg** [comment]
I updated the buildpack to use `java-function-invoker-0.1.3-20181113.211813-2-exec.jar` instead and that seems to work. Something must have gotten messed up when I uploaded the snapshot versions of the invoker.
