### ISSUE TITLE
Not able to use "Message" in function signature

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#191]
Trying to write a function that uses `org.springframework.messaging.Message` in the signature and get en error that looks like a class loading issue.

```
class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @1fbc7afb; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @31ff6309)
```

The function:
```
	@Bean
	public Function<Message<String>, Message<String>> hello() {
		return (in) -> {
			System.out.println("HEADERS: " + in.getHeaders());
			Object type = in.getHeaders().get("ce-type");
			Object id = in.getHeaders().get("ce-id");
			return MessageBuilder.withPayload("Processed " + type + ":" + id).build();
		};
	}
```

Source is here: https://github.com/trisberg/riff-java-samples/tree/master/hello-message

<details>
 <summary>logs with stack trace</summary>

```
$ k logs -c user-container hello-message-deployer-547x7-bmjrm-deployment-5ccff67f9c-2l8w9
Container memory limit unset. Configuring JVM for 1G container.
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=87888K -XX:ReservedCodeCacheSize=240M -Xss1M -Xmx448687K (Head Room: 0%, Loaded Class Count: 13103, Thread Count: 250, Total Memory: 1073741824)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.4.RELEASE)

20:26:08.964 [main] INFO  i.p.invoker.main.EntryPoint - Starting EntryPoint on hello-message-deployer-547x7-bmjrm-deployment-5ccff67f9c-2l8w9 with PID 43 (/layers/io.projectriff.java/riff-invoker-java/BOOT-INF/classes started by cnb in /workspace)
20:26:08.975 [main] INFO  i.p.invoker.main.EntryPoint - No active profile set, falling back to default profiles: default
20:26:10.992 [main] INFO  o.s.c.f.d.FunctionDeployerConfiguration - Deploying archive: /workspace

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.4.RELEASE)

2020-02-18 20:26:12.284  INFO 43 --- [           main] o.s.boot.SpringApplication               : Starting application on hello-message-deployer-547x7-bmjrm-deployment-5ccff67f9c-2l8w9 with PID 43 (/workspace/BOOT-INF/lib/spring-cloud-function-web-3.0.1.RELEASE.jar started by cnb in /workspace)
2020-02-18 20:26:12.299  INFO 43 --- [           main] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2020-02-18 20:26:14.406  INFO 43 --- [           main] o.s.boot.SpringApplication               : Started application in 3.143 seconds (JVM running for 7.92)
20:26:14.412 [main] INFO  o.s.c.f.d.FunctionArchiveDeployer - Application context for archive 'file:/workspace/' is created.
20:26:14.446 [main] INFO  o.s.c.f.d.FunctionArchiveDeployer - Discovered functions in deployed application context: {functionRouter=org.springframework.cloud.function.context.config.RoutingFunction@1b7554d4, hello=functions.HelloMessageApplication$$Lambda$515/0x00000001005dd040@57ce2898}
20:26:14.455 [main] INFO  o.s.c.f.d.FunctionArchiveDeployer - Registering function 'functionRouter' of type 'class org.springframework.cloud.function.context.config.RoutingFunction' in FunctionRegistry.
20:26:14.460 [main] INFO  o.s.c.f.d.FunctionArchiveDeployer - Registering function 'hello' of type 'java.util.function.Function<org.springframework.messaging.Message<java.lang.String>, org.springframework.messaging.Message<java.lang.String>>' in FunctionRegistry.
20:26:14.460 [main] INFO  o.s.c.f.d.FunctionDeployerConfiguration - Successfully deployed archive: /workspace
20:26:14.562 [main] INFO  i.p.invoker.main.EntryPoint - Started EntryPoint in 6.626 seconds (JVM running for 8.076)
20:26:28.942 [grpc-default-executor-0] INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry - Looking up function 'hello' with acceptedOutputTypes: [text/plain]
io.grpc.StatusException: UNKNOWN: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at io.grpc.Status.asException(Status.java:541)
	at io.projectriff.invoker.server.GrpcServerAdapter.lambda$invoke$0(GrpcServerAdapter.java:70)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6430)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.onNext(FluxGroupBy.java:670)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:205)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:176)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:154)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstInner.onNext(FluxSwitchOnFirst.java:184)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drainRegular(AbstractStreamObserverAndPublisher.java:191)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drain(AbstractStreamObserverAndPublisher.java:271)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.onNext(AbstractStreamObserverAndPublisher.java:315)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.invokeFunction(BeanFactoryAwareFunctionRegistry.java:497)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.lambda$doApply$1(BeanFactoryAwareFunctionRegistry.java:541)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	... 24 more
io.grpc.StatusException: UNKNOWN: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at io.grpc.Status.asException(Status.java:541)
	at io.projectriff.invoker.server.GrpcServerAdapter.lambda$invoke$0(GrpcServerAdapter.java:70)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6430)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.onNext(FluxGroupBy.java:670)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:205)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:176)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:154)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstInner.onNext(FluxSwitchOnFirst.java:184)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drainRegular(AbstractStreamObserverAndPublisher.java:191)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drain(AbstractStreamObserverAndPublisher.java:271)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.onNext(AbstractStreamObserverAndPublisher.java:315)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.invokeFunction(BeanFactoryAwareFunctionRegistry.java:497)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.lambda$doApply$1(BeanFactoryAwareFunctionRegistry.java:541)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	... 24 more
20:26:29.222 [grpc-default-executor-0] INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry - Looking up function 'hello' with acceptedOutputTypes: [text/plain]
20:26:29.243 [grpc-default-executor-0] INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry - Looking up function 'hello' with acceptedOutputTypes: [text/plain]
io.grpc.StatusException: UNKNOWN: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at io.grpc.Status.asException(Status.java:541)
	at io.projectriff.invoker.server.GrpcServerAdapter.lambda$invoke$0(GrpcServerAdapter.java:70)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6430)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.onNext(FluxGroupBy.java:670)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:205)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:176)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:154)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstInner.onNext(FluxSwitchOnFirst.java:184)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drainRegular(AbstractStreamObserverAndPublisher.java:191)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drain(AbstractStreamObserverAndPublisher.java:271)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.onNext(AbstractStreamObserverAndPublisher.java:315)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.invokeFunction(BeanFactoryAwareFunctionRegistry.java:497)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.lambda$doApply$1(BeanFactoryAwareFunctionRegistry.java:541)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	... 24 more
io.grpc.StatusException: UNKNOWN: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at io.grpc.Status.asException(Status.java:541)
	at io.projectriff.invoker.server.GrpcServerAdapter.lambda$invoke$0(GrpcServerAdapter.java:70)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6430)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:247)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:554)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:630)
	at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.onNext(FluxGroupBy.java:670)
	at reactor.core.publisher.FluxGroupBy$GroupByMain.onNext(FluxGroupBy.java:205)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:176)
	at io.projectriff.invoker.server.GrpcServerAdapter$1.onNext(GrpcServerAdapter.java:154)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:176)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:80)
	at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstInner.onNext(FluxSwitchOnFirst.java:184)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drainRegular(AbstractStreamObserverAndPublisher.java:191)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.drain(AbstractStreamObserverAndPublisher.java:271)
	at com.salesforce.reactivegrpc.common.AbstractStreamObserverAndPublisher.onNext(AbstractStreamObserverAndPublisher.java:315)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:251)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:309)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:292)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class org.springframework.messaging.support.GenericMessage cannot be cast to class org.springframework.messaging.Message (org.springframework.messaging.support.GenericMessage is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5e025e70; org.springframework.messaging.Message is in unnamed module of loader org.springframework.cloud.function.deployer.FunctionArchiveDeployer$1 @14d8444b)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.invokeFunction(BeanFactoryAwareFunctionRegistry.java:497)
	at org.springframework.cloud.function.context.catalog.BeanFactoryAwareFunctionRegistry$FunctionInvocationWrapper.lambda$doApply$1(BeanFactoryAwareFunctionRegistry.java:541)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	... 24 more
20:26:29.367 [grpc-default-executor-0] INFO  o.s.c.f.c.c.BeanFactoryAwareFunctionRegistry - Looking up function 'hello' with acceptedOutputTypes: [text/plain]
```
</details>

**Comment by ericbottard** [comment]
I created a testcase for that [here](https://github.com/ericbottard/java-function-invoker/commit/c344f3087d1294dd7fad6a58c7b984311fa87f81).

I wonder what you think about this @olegz. Excluding the spring-messaging jar from the function doesn't seem to fix the issue (gotta admit I tried it without thinking much about it), so must be more subtle.

**Comment by olegz** [comment]
It appears that we can load `org.springframework.messaging.Message` (and possibly other messaging strategies) using common class loader (similar to the reactive libraries). 

NOTE: I am ***only*** implying specific strategies and not the entire messaging JAR. Basically part of the issue why we can't share the entire messaging JAR is because two sides may have some shared classes that have already been loaded by different class loaders. However, at the pure strategy level (e.g., `Message`) we're fine as long as the structure of such strategies changes.

**Comment by olegz** [comment]
was able to reproduce the issue and it is addressed here - https://github.com/spring-cloud/spring-cloud-function/commit/202d617edde63985ac3c2508d4bfdf912cdf000c
