### ISSUE TITLE
Chaining two Java functions cause rpc error

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#62]
If I  chain the output from a Java function to another Java function I get an rpc error. It works if the first function is a command like the echo sample.

The error:

```
$ riff logs -n uppercase
Displaying logs for container sidecar of function uppercase in namespace 

2018/04/06 00:45:28 Sidecar for function 'uppercase' (uppercase->replies) using grpc dispatcher starting
2018/04/06 00:45:28 Rebalanced: &{Type:rebalance start Claimed:map[] Released:map[] Current:map[]}
2018/04/06 00:45:28 Rebalanced: &{Type:rebalance OK Claimed:map[uppercase:[0]] Released:map[] Current:map[uppercase:[0]]}
2018/04/06 00:45:37 >>> Message{tset, map[timestamp:[1522975527095] correlationId:[d9829319-fee2-452b-8082-f7fc3834bbb4] Content-Type:[text/plain]]}
2018/04/06 00:45:38 Error receiving message from function: rpc error: code = Unknown desc = 
2018/04/06 00:45:38 Error receiving message from function: rpc error: code = Unknown desc = 
2018/04/06 00:45:38 Error receiving message from function: rpc error: code = Unknown desc = 
2018/04/06 00:45:38 Error receiving message from function: rpc error: code = Unknown desc = 
2018/04/06 00:45:38 Error receiving message from function: rpc error: code = Unknown desc = 
2018/04/06 00:45:38 Error receiving message from function: rpc error: code = Unknown desc = 
```

**Comment by trisberg** [comment]
Looks like a 'timestamp' header gets passed along to the new message and this header is read-only.

Adding the main containers logs:

```
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:25 >>> Message{test, map[correlationId:[28d515bb-65fe-4a61-a4ae-23624fa4fb8e] Content-Type:[text/plain] timestamp:[1523292313856]]}
default/uppercase-847cd444bf-gc8lp[main]: [DEBUG] (grpc-default-executor-0) Using Console logging
default/uppercase-847cd444bf-gc8lp[main]: 2018-04-09 16:45:31.398 ERROR 1 --- [ault-executor-0] io.grpc.internal.SerializingExecutor     : Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@11da0f65
default/uppercase-847cd444bf-gc8lp[main]: 
default/uppercase-847cd444bf-gc8lp[main]: java.lang.IllegalArgumentException: 'timestamp' header is read-only
default/uppercase-847cd444bf-gc8lp[main]: 	at org.springframework.messaging.support.MessageHeaderAccessor.setHeader(MessageHeaderAccessor.java:296) ~[spring-messaging-4.3.15.RELEASE.jar:4.3.15.RELEASE]
default/uppercase-847cd444bf-gc8lp[main]: 	at org.springframework.messaging.support.MessageBuilder.setHeader(MessageBuilder.java:77) ~[spring-messaging-4.3.15.RELEASE.jar:4.3.15.RELEASE]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.projectriff.invoker.MessageConversionUtils.fromGrpc(MessageConversionUtils.java:52) ~[app/:na]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer$1.onNext(JavaFunctionInvokerServer.java:135) ~[app/:na]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer$1.onNext(JavaFunctionInvokerServer.java:129) ~[app/:na]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) ~[grpc-stub-1.8.0.jar:1.8.0]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:251) ~[grpc-core-1.8.0.jar:1.8.0]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:624) ~[grpc-core-1.8.0.jar:1.8.0]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.8.0.jar:1.8.0]
default/uppercase-847cd444bf-gc8lp[main]: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.8.0.jar:1.8.0]
default/uppercase-847cd444bf-gc8lp[main]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
default/uppercase-847cd444bf-gc8lp[main]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
default/uppercase-847cd444bf-gc8lp[main]: 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
default/uppercase-847cd444bf-gc8lp[main]: 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
default/uppercase-847cd444bf-gc8lp[sidecar]: 2018/04/09 16:45:31 Error receiving message from function: rpc error: code = Unknown desc = 
```
