### ISSUE TITLE
Using Supplier<Flux<>> causes IllegalStateException and rpc errors

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#67]
Using something like the following for a function/supplier fails:

```
public class SourceFunction implements Supplier<Flux<String>> {

	EmitterProcessor<String> records = EmitterProcessor.create();

	@Override
	public Flux<String> get() {
		records.onNext("Init");
		return records;
	}
}
```

Switching to `implements Function<Flux<String>, Flux<String>>` with a `Flux<String> apply(Flux<String> stringFlux)` method works and doesn't show any errors.

Log output:

```
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:25 Sidecar for function 'my-flux' (my-flux->replies) using grpc dispatcher starting
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:25 Rebalanced: &{Type:rebalance start Claimed:map[] Released:map[] Current:map[]}
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:25 Rebalanced: &{Type:rebalance OK Claimed:map[my-flux:[0]] Released:map[] Current:map[my-flux:[0]]}
default/my-flux-78dbbd5f57-nmt96[main]: 
default/my-flux-78dbbd5f57-nmt96[main]:                 ▄      ▄█▀▀██▄█▀▀██
default/my-flux-78dbbd5f57-nmt96[main]:                 ▄▄▄    ██  ▀▀██  ▀▀
default/my-flux-78dbbd5f57-nmt96[main]:                ████ ▐█████████████
default/my-flux-78dbbd5f57-nmt96[main]:               ▐█▀▀▀   ▐██    ██
default/my-flux-78dbbd5f57-nmt96[main]:    █████▄▄▄▄  ▐█      ▐██    ██
default/my-flux-78dbbd5f57-nmt96[main]:     ▐██   ██  ▐█      ▐██    ██
default/my-flux-78dbbd5f57-nmt96[main]:     ▐██       ▐█     ▀▀▀▀▀  ▀▀▀▀▀
default/my-flux-78dbbd5f57-nmt96[main]:     ▐██       ▐█
default/my-flux-78dbbd5f57-nmt96[main]:    ▄███▄▄      
default/my-flux-78dbbd5f57-nmt96[main]: 
default/my-flux-78dbbd5f57-nmt96[main]: :: Powered by Spring Boot ::         (v1.5.11.RELEASE)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:25 PM org.springframework.boot.StartupInfoLogger logStarting
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Starting application on my-flux-78dbbd5f57-nmt96 with PID 1 (/app started by root in /)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:25 PM org.springframework.boot.SpringApplication logStartupProfileInfo
default/my-flux-78dbbd5f57-nmt96[main]: INFO: No active profile set, falling back to default profiles: default
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:25 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7686f136: startup date [Wed Apr 11 19:43:25 GMT 2018]; root of context hierarchy
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer initialize
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Tomcat initialized with port(s): 8080 (http)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.apache.catalina.core.StandardService startInternal
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Starting service [Tomcat]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.apache.catalina.core.StandardEngine startInternal
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Starting Servlet Engine: Apache Tomcat/8.5.29
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.apache.catalina.core.ApplicationContext log
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Initializing Spring embedded WebApplicationContext
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.context.embedded.EmbeddedWebApplicationContext prepareEmbeddedWebApplicationContext
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Root WebApplicationContext: initialization completed in 1374 ms
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.web.servlet.ServletRegistrationBean onStartup
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapping servlet: 'dispatcherServlet' to [/]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapping filter: 'characterEncodingFilter' to: [/*]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapping filter: 'httpPutFormContentFilter' to: [/*]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.boot.web.servlet.AbstractFilterRegistrationBean configure
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapping filter: 'requestContextFilter' to: [/*]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM io.projectriff.invoker.FunctionProperties init
default/my-flux-78dbbd5f57-nmt96[main]: INFO: initializing with uri: file:///functions/my-flux-0.0.1.jar?handler=com.springdeveloper.streams.demo.SourceFunction
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM io.projectriff.invoker.FunctionConfiguration$BeanCreator create
default/my-flux-78dbbd5f57-nmt96[main]: INFO: No main class provided. Instantiating: com.springdeveloper.streams.demo.SourceFunction
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter initControllerAdviceCache
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7686f136: startup date [Wed Apr 11 19:43:25 GMT 2018]; root of context hierarchy
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry register
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped "{[/],methods=[POST]}" onto public java.lang.String io.projectriff.invoker.JavaFunctionInvokerController.invoke()
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry register
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry register
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.handler.AbstractUrlHandlerMapping registerHandler
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.handler.AbstractUrlHandlerMapping registerHandler
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:27 PM org.springframework.web.servlet.handler.AbstractUrlHandlerMapping registerHandler
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM org.springframework.cloud.function.web.flux.FunctionHandlerMapping <init>
default/my-flux-78dbbd5f57-nmt96[main]: INFO: FunctionCatalog: org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration$BeanFactoryFunctionCatalog@d132049
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry register
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped "{[/**],methods=[POST]}" onto public org.springframework.http.ResponseEntity<org.reactivestreams.Publisher<?>> org.springframework.cloud.function.web.flux.FunctionController.post(org.springframework.web.context.request.WebRequest,org.springframework.cloud.function.web.flux.request.FluxRequest<?>)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$MappingRegistry register
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Mapped "{[/**],methods=[GET]}" onto public org.reactivestreams.Publisher<?> org.springframework.cloud.function.web.flux.FunctionController.get(org.springframework.web.context.request.WebRequest)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM io.projectriff.invoker.GrpcConfiguration start
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Server started, listening on 10382
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer start
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Tomcat started on port(s): 8080 (http)
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM io.projectriff.invoker.BeanCountingApplicationListener onApplicationEvent
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Bean count: application=118
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM io.projectriff.invoker.BeanCountingApplicationListener onApplicationEvent
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Class count: application=5347
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM io.projectriff.invoker.BeanCountingApplicationListener onApplicationEvent
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Invoker app started
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:28 PM org.springframework.boot.StartupInfoLogger logStarted
default/my-flux-78dbbd5f57-nmt96[main]: INFO: Started application in 2.807 seconds (JVM running for 3.404)
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 >>> Message{1, map[Content-Type:[text/plain]]}
default/my-flux-78dbbd5f57-nmt96[main]: [DEBUG] (grpc-default-executor-0) Using Console logging
default/my-flux-78dbbd5f57-nmt96[main]: 19:43:30.824 [grpc-default-executor-0] INFO com.springdeveloper.streams.demo.SourceFunction - *** [FUNC] Called!
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 <<< Message{Init: 1, map[timestamp:[1523475810836]]}
default/my-flux-78dbbd5f57-nmt96[main]: Apr 11, 2018 7:43:30 PM io.grpc.internal.SerializingExecutor run
default/my-flux-78dbbd5f57-nmt96[main]: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@6823210
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[main]: java.lang.IllegalStateException: Cannot convert to class java.lang.Void
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer.fromBytes(JavaFunctionInvokerServer.java:194)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer.payloadFromBytes(JavaFunctionInvokerServer.java:176)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.projectriff.default/my-flux-78dbbd5f57-nmt96[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer$1.onNext(JavaFunctionInvokerServer.java:135)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer$1.onNext(JavaFunctionInvokerServer.java:129)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:251)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:624)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
default/my-flux-78dbbd5f57-nmt96[main]: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[main]: 	... 12 more
default/my-flux-78dbbd5f57-nmt96[main]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 2 path $
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[main]: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
default/my-flux-78dbbd5f57-nmt96[main]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
default/my-flux-78dbbd5f57-nmt96[main]: 	... 17 more
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[main]: 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
default/my-flux-78dbbd5f57-nmt96[sidecar]: 2018/04/11 19:43:30 Error receiving message from function: rpc error: code = Unknown desc = 
```

**Comment by dsyer** [comment]
It looks like maybe you sent a message on the input channel for this function (kind of doesn't make sense for a Supplier)?

**Comment by dsyer** [comment]
There's a test now (in 020f472) so I know this works.
