### ISSUE TITLE
Ugly half-closed exception when container terminates

### ISSUE THREAD

**Issue by dsyer** [projectriff/java-function-invoker#68]
Probably harmless, but ugly:

```
default/uppercase-c579ccb48-bdrlj[sidecar]: 2018/04/16 08:45:18 Shutting Down...
default/uppercase-c579ccb48-bdrlj[main]: Apr 16, 2018 8:45:18 AM io.grpc.internal.SerializingExecutor run
default/uppercase-c579ccb48-bdrlj[main]: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@be5a4128
default/uppercase-c579ccb48-bdrlj[main]: java.lang.IllegalStateException: io.grpc.StatusException: INTERNAL: CANCELLED: cancelled before receiving half close
default/uppercase-c579ccb48-bdrlj[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer.lambda$9(JavaFunctionInvokerServer.java:120)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer$$Lambda$52.000000004802D980.accept(Unknown Source)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.LambdaSubscriber.onError(LambdaSubscriber.java:119)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:126)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.UnicastProcessor.checkTerminated(UnicastProcessor.java:291)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:189)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:269)
default/uppercase-c579ccb48-bdrlj[main]: 	at reactor.core.publisher.UnicastProcessor.onError(UnicastProcessor.java:358)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer$1.onError(JavaFunctionInvokerServer.java:140)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:269)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:281)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:679)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
default/uppercase-c579ccb48-bdrlj[main]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
default/uppercase-c579ccb48-bdrlj[main]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
default/uppercase-c579ccb48-bdrlj[main]: 	at java.lang.Thread.run(Thread.java:812)
default/uppercase-c579ccb48-bdrlj[main]: Caused by: io.grpc.StatusException: INTERNAL: CANCELLED: cancelled before receiving half close
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.Status.asException(Status.java:534)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.projectriff.invoker.JavaFunctionInvokerServer.lambda$9(JavaFunctionInvokerServer.java:121)
default/uppercase-c579ccb48-bdrlj[main]: 	... 20 more
default/uppercase-c579ccb48-bdrlj[main]: Caused by: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.Status.asRuntimeException(Status.java:517)
default/uppercase-c579ccb48-bdrlj[main]: 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272)
default/uppercase-c579ccb48-bdrlj[main]: 	... 7 more
```

I can only reproduce this when using openj9 as a base image for the java invoker. Probably not such a big deal, given that is not the default. But worth looking into at some point.

**Comment by scothis** [comment]
stale
